### ISSUE TITLE
Multiple Timeframe workaround/support

### ISSUE THREAD

**Issue by arminvandam1980** [afhacker/NetTrade#1]
Hello Ahmad,

First of all I want to thank you for all your great work in all these repositories.

I don't know if you still have time for this NetTrade project. If so, I would like to know if it is possible to use more than one timeframe (or `IEnumerable<IBar>`) in a Robot. I would like to make a robot that can have multiple `IEnumerable<IBar>` without losing current functionalities like optimization and backtesting.
Is there an easy workaround for this?

Thanks a lot,
Armin

**Comment by amusleh-spotware-com** [comment]
Hi,

Sorry, I don't remember if I implemented multi time frame feature or not, it was very long time ago.

If I didn't then you can do it easily by yourself and I will love to merge your PR if you did.
